import React, { useState, useEffect } from "react";
import { Task } from "../types";
import {
  Plus,
  Check,
  X,
  Calendar as CalendarIcon,
  AlertCircle,
  Sparkles,
  ChevronDown,
  ChevronUp
} from "lucide-react";
import { CalendarPicker } from "./CalendarPicker";
import { AnalogClockPicker } from "./AnalogClockPicker";

interface TaskFormProps {
  onSave: (taskData: {
    title: string;
    description: string;
    priority: "high" | "medium" | "low";
    dueDateTime: string;
    syncToCalendar?: boolean;
  }) => Promise<void>;
  editingTask: Task | null;
  onCancelEdit: () => void;
  calendarConnected: boolean;
}

export const TaskForm: React.FC<TaskFormProps> = ({
  onSave,
  editingTask,
  onCancelEdit,
  calendarConnected,
}) => {
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [priority, setPriority] = useState<"high" | "medium" | "low">("medium");

  // In-memory date state
  const [taskDate, setTaskDate] = useState<Date>(() => {
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    tomorrow.setHours(12, 0, 0, 0);
    return tomorrow;
  });

  const [showDateTimePicker, setShowDateTimePicker] = useState(false);
  const [syncToCalendar, setSyncToCalendar] = useState(calendarConnected);
  
  const [isLoading, setIsLoading] = useState(false);
  const [isEnhancing, setIsEnhancing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successMsg, setSuccessMsg] = useState<string | null>(null);

  useEffect(() => {
    if (editingTask) {
      setTitle(editingTask.title);
      setDescription(editingTask.description);
      setPriority(editingTask.priority);
      setTaskDate(new Date(editingTask.dueDateTime));
      setSyncToCalendar(!!editingTask.calendarEventId);
    } else {
      resetForm();
    }
  }, [editingTask, resetForm]);

  const resetForm = useCallback(() => {
    setTitle("");
    setDescription("");
    setPriority("medium");
    const tomorrow = new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    tomorrow.setHours(12, 0, 0, 0);
    setTaskDate(tomorrow);
    setSyncToCalendar(calendarConnected);
    setError(null);
    setSuccessMsg(null);
  }, [calendarConnected]);

  // Enhance using Gemini API route
  const handleAiEnhance = async () => {
    if (!title.trim()) {
      setError("Please write a task name first so Gemini has context to generate details!");
      return;
    }

    setIsEnhancing(true);
    setError(null);
    setSuccessMsg(null);

    try {
      const response = await fetch("/api/gemini/enhance", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ title }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate task details.");
      }

      if (data.description) {
        setDescription(data.description);
      }
      if (data.priority) {
        setPriority(data.priority as "high" | "medium" | "low");
      }
      setSuccessMsg("Details & priority generated by Gemini!");
      setTimeout(() => setSuccessMsg(null), 3500);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "An unexpected error occurred while calling Gemini API.");
    } finally {
      setIsEnhancing(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) {
      setError("Please provide a task title.");
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      await onSave({
        title,
        description,
        priority,
        dueDateTime: taskDate.toISOString(),
        syncToCalendar: calendarConnected ? syncToCalendar : false,
      });

      if (!editingTask) {
        resetForm();
      }
    } catch (err: any) {
      console.error(err);
      setError(err.message || "An error occurred while saving the task.");
    } finally {
      setIsLoading(false);
    }
  };

  // Human friendly datetime format helper
  const getFormattedDateTimeLabel = () => {
    return taskDate.toLocaleString(undefined, {
      weekday: "short",
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  return (
    <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm text-left relative" id="task-form-panel">
      
      {/* Form Header */}
      <div className="flex items-center justify-between mb-5">
        <h2 className="font-bold text-slate-800 text-base flex items-center gap-2">
          <Plus className="w-5 h-5 text-indigo-600" />
          {editingTask ? "Modify Task Profile" : "Create Manual Task"}
        </h2>
        {editingTask && (
          <button
            onClick={onCancelEdit}
            className="p-1.5 hover:bg-slate-100 rounded text-slate-500 hover:text-slate-800 transition-colors cursor-pointer"
            id="cancel-edit-btn"
          >
            <X className="w-4 h-4" />
          </button>
        )}
      </div>

      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Title & Gemini button inside */}
        <div>
          <label className="block text-xs font-bold uppercase text-slate-500 tracking-wider mb-1.5">
            Task Name
          </label>
          <div className="relative">
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Brainstorm launch tactics"
              className="w-full bg-slate-50 border border-slate-200 rounded-xl pl-4 pr-32 py-2.5 text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:bg-white transition-all"
              disabled={isLoading || isEnhancing}
              required
              id="task-title-input"
            />
            {/* Gemini enhance trigger */}
            <button
              type="button"
              onClick={handleAiEnhance}
              disabled={isEnhancing || !title.trim()}
              className="absolute right-2 top-1/2 -translate-y-1/2 bg-indigo-50 hover:bg-indigo-100 text-indigo-600 px-3 py-1.5 rounded-lg text-xs font-bold transition-all border border-indigo-100 hover:border-indigo-200 flex items-center gap-1 cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed"
              title="Generate details and logical priority using Gemini AI"
              id="ai-enhance-btn"
            >
              <Sparkles className="w-3.5 h-3.5 animate-pulse" />
              <span>{isEnhancing ? "Drafting..." : "AI Suggest"}</span>
            </button>
          </div>
        </div>

        {/* Description / Notes */}
        <div>
          <div className="flex justify-between items-center mb-1.5">
            <label className="block text-xs font-bold uppercase text-slate-500 tracking-wider">
              Details & Notes
            </label>
            {successMsg && (
              <span className="text-[10px] text-emerald-600 font-bold bg-emerald-50 px-2 py-0.5 rounded border border-emerald-100">
                {successMsg}
              </span>
            )}
          </div>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Describe the objective, prerequisites, or run sheets... (Or use Gemini AI helper above to autofill!)"
            className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-2.5 text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:bg-white min-h-[85px] resize-none transition-all"
            disabled={isLoading || isEnhancing}
            id="task-description-input"
          />
        </div>

        {/* Priority & Scheduling Selectors */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          
          {/* Priority */}
          <div>
            <label className="block text-xs font-bold uppercase text-slate-500 tracking-wider mb-1.5">
              Priority (AI Recommended)
            </label>
            <select
              value={priority}
              onChange={(e) => setPriority(e.target.value as any)}
              className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3 py-2.5 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:bg-white cursor-pointer transition-all"
              disabled={isLoading || isEnhancing}
              id="task-priority-select"
            >
              <option value="high">🔥 High Priority</option>
              <option value="medium">⚡ Medium Priority</option>
              <option value="low">🌱 Low Priority</option>
            </select>
          </div>

          {/* Due DateTime trigger label */}
          <div>
            <label className="block text-xs font-bold uppercase text-slate-500 tracking-wider mb-1.5">
              Due Date & Time
            </label>
            <button
              type="button"
              onClick={() => setShowDateTimePicker(!showDateTimePicker)}
              className="w-full bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded-xl px-3.5 py-2.5 text-sm text-slate-700 font-medium flex items-center justify-between cursor-pointer transition-all focus:outline-none focus:ring-2 focus:ring-indigo-500/20"
              id="custom-date-trigger-btn"
            >
              <span className="flex items-center gap-2">
                <CalendarIcon className="w-4 h-4 text-indigo-500" />
                {getFormattedDateTimeLabel()}
              </span>
              {showDateTimePicker ? (
                <ChevronUp className="w-4 h-4 text-slate-400" />
              ) : (
                <ChevronDown className="w-4 h-4 text-slate-400" />
              )}
            </button>
          </div>

        </div>

        {/* Inline Custom Calendar & Analog Clock Picker Panel */}
        {showDateTimePicker && (
          <div className="bg-slate-50/50 border border-slate-200 rounded-2xl p-4 grid grid-cols-1 md:grid-cols-2 gap-4 animate-fadeIn" id="custom-date-time-picker-panel">
            {/* Calendar */}
            <div className="space-y-2">
              <span className="text-[10px] font-extrabold uppercase text-slate-400 tracking-wider block">
                1. Select Calendar Date
              </span>
              <CalendarPicker selectedDate={taskDate} onChange={(newDate) => setTaskDate(newDate)} />
            </div>

            {/* Analog Clock */}
            <div className="space-y-2">
              <span className="text-[10px] font-extrabold uppercase text-slate-400 tracking-wider block">
                2. Select Time (Analog Face)
              </span>
              <AnalogClockPicker selectedDate={taskDate} onChange={(newDate) => setTaskDate(newDate)} />
            </div>

            {/* Done button */}
            <div className="md:col-span-2 flex justify-end">
              <button
                type="button"
                onClick={() => setShowDateTimePicker(false)}
                className="px-4 py-1.5 bg-indigo-50 border border-indigo-200 text-indigo-600 hover:bg-indigo-100 rounded-lg text-xs font-bold transition-all cursor-pointer"
              >
                Apply Timing
              </button>
            </div>
          </div>
        )}

        {/* Sync checkbox */}
        {calendarConnected && (
          <div className="pt-2">
            <label className="inline-flex items-center gap-2 cursor-pointer text-xs font-medium text-slate-600 hover:text-slate-800 transition-colors">
              <input
                type="checkbox"
                checked={syncToCalendar}
                onChange={(e) => setSyncToCalendar(e.target.checked)}
                className="rounded border-slate-250 bg-white text-indigo-600 focus:ring-indigo-500/20 w-4 h-4 cursor-pointer"
                disabled={isLoading}
              />
              <span className="flex items-center gap-1.5">
                <CalendarIcon className="w-3.5 h-3.5 text-indigo-500" />
                Sync directly with Google Calendar
              </span>
            </label>
          </div>
        )}

        {/* Error notification */}
        {error && (
          <div className="bg-rose-50 border border-rose-100 text-rose-600 text-xs p-3.5 rounded-xl flex items-start gap-2 animate-fadeIn">
            <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
            <span>{error}</span>
          </div>
        )}

        {/* Action Button Suite */}
        <div className="flex justify-end gap-3 pt-3 border-t border-slate-100">
          {editingTask && (
            <button
              type="button"
              onClick={onCancelEdit}
              className="px-4 py-2 bg-slate-100 hover:bg-slate-200 border border-slate-200 text-slate-600 rounded-xl text-sm font-semibold transition-all cursor-pointer"
              disabled={isLoading || isEnhancing}
              id="task-cancel-btn"
            >
              Cancel
            </button>
          )}

          <button
            type="submit"
            disabled={isLoading || isEnhancing}
            className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-sm rounded-xl shadow-md shadow-indigo-100 hover:shadow-indigo-200 hover:-translate-y-0.5 transition-all flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
            id="task-submit-btn"
          >
            {editingTask ? (
              <>
                <Check className="w-4 h-4 stroke-[2.5]" />
                <span>Update Task</span>
              </>
            ) : (
              <>
                <Plus className="w-4 h-4 stroke-[2.5]" />
                <span>Add Task to Schedule</span>
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
};
